### ISSUE TITLE
explanation

### ISSUE THREAD

**Issue by noraj** [teknogeek/ssrf-sheriff#1]
Looks interesting.

Can you explain what a "sheriff" is? Is that like a SSRF mockup server?

**Comment by teknogeek** [comment]
Hey @noraj,

>Is that like a SSRF mockup server?

Yes, that's basically correct. The idea is that you can run this inside your infrastructure to allow researchers to easily test SSRF vulnerabilities without risking real data exposure. Additionally, since the response contains a secret value, it makes it much easier to provide proof that you could _actually_ hit an internal service (and there are logs for all the requests being handled, i.e. for blind SSRFs)

Hopefully, that answers your question :)

**Comment by noraj** [comment]
thx for the answer
